### ISSUE TITLE
Doesn't work in Internet Explorer

### ISSUE THREAD

**Issue by mattlewis92** [kamilkp/angular-vs-repeat#48]
The demo doesn't work in IE (I tested on both 9 and 11). It seems to just display the last element in the list :(

Any chance of a fix?

**Comment by kamilkp** [comment]
Will look into it tomorrow

**Comment by mattlewis92** [comment]
Thank you :)

**Comment by mato75** [comment]
Please do fix!

**Comment by kamilkp** [comment]
fixed. make sure you have the new (rc8) version

**Comment by mattlewis92** [comment]
Thanks for the quick fix! However it still doesn't seem to be quite working, after starting scrolling only half the content is visible
![screen shot 2015-05-29 at 11 53 07](https://cloud.githubusercontent.com/assets/6425649/7881285/6aa169fe-05f9-11e5-82ce-8da32968f9dd.png)

**Comment by kamilkp** [comment]
Hmm, doesn't happen in my IE. I use IE 11

**Comment by mattlewis92** [comment]
I've tried it in both IE9 and IE11 on windows 7 (in emulators). I'm also getting similar behaviour on firefox on a mac
![screen shot 2015-05-29 at 12 26 08](https://cloud.githubusercontent.com/assets/6425649/7881735/f4b29588-05fd-11e5-93cf-8d18f70c743a.png)

**Comment by kamilkp** [comment]
Works well on FF on my machine too. I also use Mac OS and test in IE in VMs. Does this also happen on other tabs in the demo?

**Comment by mattlewis92** [comment]
It only happens in the performance tab. If I scroll really slowly it works ok, but as soon as I start scrolling fast or using the scrollbar to scroll it breaks. I'll try it on my integration within my app and see if it works.

**Comment by kamilkp** [comment]
ok

**Comment by mattlewis92** [comment]
Just tested it on our app and it's working flawlessly in IE 9 - 11 :) 

I did have one small trip up as I was using track by on the ng-repeat and it broke the scroller (although weirdly it worked in the previous version). You might want to add a note to the docs about that, as well as not using one time binding.

Thanks again for a great plugin, it's made my life a lot easier! :)

**Comment by kamilkp** [comment]
> I was using track by on the ng-repeat and it broke the scroller
try with the most recent version - I recommend downloading the one from the tip of the master branch from github website directly (there was a bug but i fixed it recently)

**Comment by mattlewis92** [comment]
Yup it works with master. You might want to release a new version still as if anyone's using this library with an automated build system it might break their app. Something similar happened to me before with the ui-router
